### ISSUE TITLE
PHPCBF applies PHP fixes to XML files

### ISSUE THREAD

**Issue by boldhedgehog** [YouweGit/coding-standard-magento2#7]
The presence of `xml/XML` in the extensions argument in file `./src/YouweMagento2/ruleset.xml` makes PHPCBF corrupt XML files like this:

`<arg name="extensions" value="php/PHP,phtml/PHP,js/JS,css/CSS,xml/XML,less/CSS" />`

```xml
<?
    
xml version="1.0"?>
```

because this rule `PSR12.Files.FileHeader.SpacingAfterBlock` is being applied to XML files.

**Comment by boldhedgehog** [comment]
FYI: PHPStorm by default calls phpcbf with this argument:
`--extensions=php,js,css,inc`

**Comment by fredden** [comment]
Hi @boldhedgehog. Thanks for raising this. I have run `vendor/bin/phpcbf --standard=YouweMagento2 src/YouweMagento2/phpmd.xml` in this repository and get a message saying that "No fixable errors were found". Do you have an example XML file and command that I can run to see this bug in action?

**Comment by boldhedgehog** [comment]
@fredden If I reproduce this next time, I'll create another issue, this one can be closed.
